### ISSUE TITLE
Change header of "Content-Type" to "application/octet-stream" for tgo-packages group of endpoints

### ISSUE THREAD

**Issue by panstav1** [sonata-nfv/tng-cat#38]

**Comment by jbonnet** [comment]
@panstav1 Actually, we can be more inteligent than this (this was my idea, so... :-)): every file in the package descriptor has a MIME type (aka, content-type), e.g., LICENSE is text/plain. Why not setting this very same content-type when returning the file, instead of fixing its type at application/octet-stream?

**Comment by panstav1** [comment]
@jbonnet so design the endpoint "packages/:uuid/files/:file_uuid" without setting the Content type header and return the corresponding content type with the fetch of the file.

**Comment by jbonnet** [comment]
Exactely. What do you think? @mpeuster what should be the client's behaviour when custom mime types are sent, plain text?Em 24/05/2018 1:09 AM, Panagiotis Stavrianos <notifications@github.com> escreveu:@jbonnet so design the endpoint "packages/:uuid/files/:file_uuid" without setting the Content type header and return the corresponding content type with the fetch of the file.

**Comment by panstav1** [comment]
@mpeuster In order to change to unified header "Content-Type: application/octet-stream", packager also needs alignment of this change

**Comment by mpeuster** [comment]
@panstav1 Yes. Just let me know when you update tng-cat to expect "Content-Type: application/octet-stream" and I change it in the tng-sdk-package code.
